# Generated by Django 4.1.5 on 2023-03-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
