# Generated by Django 4.1.5 on 2023-04-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
        ('mainapp', '0002_county_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='company_approved_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_approved_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='company_approved_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_approved_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='company_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='company_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='enumerator_approved_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enumerator_approved_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='enumerator_approved_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enumerator_approved_emailconfig', to='mailer.emailconfiguration'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='enumerator_creation_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enumerator_creation_email', to='mailer.email'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='enumerator_creation_emailconfig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enumerator_creation_emailconfig', to='mailer.emailconfiguration'),
        ),
    ]
