# Generated by Django 4.1.5 on 2023-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='files',
            field=models.ManyToManyField(blank=True, to='interact.chatfile'),
        ),
    ]
