"""
Django settings for giz_project project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z))1uk06^4ffxb@0$pq8u2tu#$rt^z2s7hpc--%15xp$4otp99'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'giz_app',
    'shop',
    'resources',
    'mailer',
    'mainapp',
    'superadmin',
    'interact',

    "bootstrap5",
    "rest_framework",
    "corsheaders",
    "django_filters",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'giz_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'giz_project.wsgi.application'

TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

COINBASE_COMMERCE_API_KEY = "557afc2f-bcb5-4411-8180-e13796f6cff4"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases


if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db2.sqlite3',
        }
    }
else:
    SECURE_SSL_REDIRECT = True
    DATABASES = {
        'default': {
            'ENGINE': 'mysql.connector.django',
            'NAME': 'gizpassi_newdjangolive',
            'USER': 'gizpassi_newdjangolive',
            'PASSWORD': '~Q&xeXN.%=W~',
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }

EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.gizpassion.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'noreply@gizpassion.com'
DEFAULT_FROM_EMAIL = 'Tunda Tamu <noreply@gizpassion.com>'
EMAIL_HOST_PASSWORD = '?}n@*43g8DBH'

ADMIN_EMAILS = ["rovinewanjala99@gmail.com"]


# CORS settings
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = [
    "POST",
    "GET",
]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static', ),)

if DEBUG:
    # Dev media storage
    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / 'media/'
else:
    # Production media storage and routing
    MEDIA_ROOT = "/home/gizpassi/media.gizpassion.com/"
    MEDIA_URL = "https://media.gizpassion.com/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
