# Generated by Django 4.1.5 on 2023-03-08 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('giz_app', '0002_aggregator_code_collectioncenter_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county'),
        ),
    ]
