# Generated by Django 4.1.5 on 2023-03-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0006_alter_input_suppliers_and_agrovets_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processors',
            options={'verbose_name_plural': 'Processors'},
        ),
    ]
