# Generated by Django 4.1.5 on 2023-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0009_remove_farmer_postal_address_farmer_coperatives'),
    ]

    operations = [
        migrations.AddField(
            model_name='processors',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
