# Generated by Django 4.1.5 on 2023-03-10 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_county_order'),
        ('giz_app', '0010_processors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processors',
            name='location',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='name',
        ),
        migrations.AddField(
            model_name='processors',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.county'),
        ),
        migrations.AddField(
            model_name='processors',
            name='sub_county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='processors/images/'),
        ),
    ]
