# Generated by Django 4.1.5 on 2023-03-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0015_profile_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coperatives',
            name='county',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='county_number',
        ),
    ]
