# Generated by Django 4.1.5 on 2023-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0016_remove_coperatives_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
