# Generated by Django 4.1.5 on 2023-03-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0017_profile_county_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='county_number',
        ),
    ]
