# Generated by Django 4.1.5 on 2023-03-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0020_collectioncenter_sub_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregator',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectioncenter',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='countygovernment',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
