# Generated by Django 4.1.5 on 2023-03-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0021_aggregator_contact_person_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumerator',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offtaker',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processors',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='processors',
            name='phone_number_contact_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
