# Generated by Django 4.1.5 on 2023-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0022_enumerator_phone_number_offtaker_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aggregator',
            name='contact_person_phone_number',
        ),
        migrations.AddField(
            model_name='countygovernment',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financialprovider',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financialprovider',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
