# Generated by Django 4.1.5 on 2023-03-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0024_rename_price_collectioncenter_price_for_grade_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncenter',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
