# Generated by Django 4.1.5 on 2023-03-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0025_collectioncenter_contact_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncenter',
            name='description',
        ),
    ]
