# Generated by Django 4.1.5 on 2023-03-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0026_remove_collectioncenter_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncenter',
            name='contact_person_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
