# Generated by Django 4.1.5 on 2023-03-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0027_alter_collectioncenter_contact_person_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='county_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
