# Generated by Django 4.1.5 on 2023-03-20 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_county_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('giz_app', '0028_farmer_county_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputSuppliersAndAgrovets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=200, null=True)),
                ('county_number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='processors/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person_phone_number', models.IntegerField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Input Suppliers And Agrovets',
            },
        ),
        migrations.CreateModel(
            name='TransportLogistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now=True)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=200, null=True)),
                ('county_number', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='processors/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person_phone_number', models.IntegerField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transport And Logistics',
            },
        ),
        migrations.RemoveField(
            model_name='transport_logistics',
            name='county',
        ),
        migrations.RemoveField(
            model_name='transport_logistics',
            name='user',
        ),
        migrations.RenameField(
            model_name='coperatives',
            old_name='phone_number_contact_person',
            new_name='contact_person_phone_number',
        ),
        migrations.RenameField(
            model_name='processors',
            old_name='phone_number_contact_person',
            new_name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='coperatives',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='coperatives',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coperatives',
            name='name',
        ),
        migrations.RemoveField(
            model_name='countygovernment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='countygovernment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='countygovernment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='countygovernment',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='financialprovider',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='financialprovider',
            name='title',
        ),
        migrations.RemoveField(
            model_name='financialprovider',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='location',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='title',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='aggregator',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county'),
        ),
        migrations.AddField(
            model_name='coperatives',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='coperatives',
            name='county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county'),
        ),
        migrations.AddField(
            model_name='coperatives',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='countygovernment',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='countygovernment',
            name='county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county'),
        ),
        migrations.AddField(
            model_name='countygovernment',
            name='sub_county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='countygovernment',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialprovider',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='financialprovider',
            name='county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county'),
        ),
        migrations.AddField(
            model_name='financialprovider',
            name='sub_county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='financialprovider',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='sub_county',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aggregator',
            name='county_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coperatives',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='processors/images/'),
        ),
        migrations.AlterField(
            model_name='countygovernment',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='countygovernment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='countygovernment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='processors/images/'),
        ),
        migrations.AlterField(
            model_name='enumerator',
            name='county_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='county_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='financialprovider',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='financialprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialprovider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='processors/images/'),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='created_on',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='processors/images/'),
        ),
        migrations.AlterField(
            model_name='processors',
            name='county',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.county'),
        ),
        migrations.AlterField(
            model_name='processors',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Input_suppliers_and_agrovets',
        ),
        migrations.DeleteModel(
            name='Transport_logistics',
        ),
    ]
