# Generated by Django 4.1.5 on 2023-03-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0029_inputsuppliersandagrovets_transportlogistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coperatives',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='coperatives',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='countygovernment',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='countygovernment',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='financialprovider',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='financialprovider',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='inputsuppliersandagrovets',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='inputsuppliersandagrovets',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='processors',
            name='contact_person_phone_number',
        ),
        migrations.RemoveField(
            model_name='transportlogistics',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='transportlogistics',
            name='contact_person_phone_number',
        ),
    ]
