# Generated by Django 4.1.5 on 2023-03-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0030_remove_coperatives_contact_person_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncenter',
            name='grade_1',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collectioncenter',
            name='grade_2',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='collectioncenter',
            name='grade_3',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
