# Generated by Django 4.1.5 on 2023-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0031_alter_collectioncenter_grade_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncenter',
            name='flashsale',
            field=models.BooleanField(default=False),
        ),
    ]
