# Generated by Django 4.1.5 on 2023-03-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0033_alter_collectioncenter_grade_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countygovernment',
            name='website',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
