# Generated by Django 4.1.5 on 2023-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0035_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumerator',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
