# Generated by Django 4.1.5 on 2023-04-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giz_app', '0037_alter_offtaker_user_company_enumerator_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
