# Generated by Django 4.1.5 on 2023-03-09 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_extensionservice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demofarm',
            name='challenges',
        ),
    ]
