# Generated by Django 4.1.5 on 2023-03-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_demofarm_image_remove_nursery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demofarm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nursery',
            name='description',
        ),
    ]
