# Generated by Django 4.1.5 on 2023-03-13 09:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0009_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Knowledge_base',
        ),
    ]
