# Generated by Django 4.1.5 on 2023-03-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_rename_video_knowledge_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledge_base',
            options={'verbose_name_plural': 'Knowledge Base'},
        ),
    ]
