# Generated by Django 4.1.5 on 2023-03-13 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_alter_knowledge_base_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge_base',
            name='image',
        ),
    ]
