# Generated by Django 4.1.5 on 2023-03-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_knowledge_base_county_knowledge_base_sub_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge_base',
            old_name='video_file',
            new_name='file',
        ),
        migrations.AddField(
            model_name='knowledge_base',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'Pdf'), ('doc', 'Doc'), ('video', 'Video'), ('image', 'image')], max_length=20, null=True),
        ),
    ]
