# Generated by Django 4.1.5 on 2023-03-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_rename_video_file_knowledge_base_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demofarm',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demofarm',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursery',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nursery',
            name='contact_person_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmergroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmergroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stakeholders/farmer-groups/'),
        ),
        migrations.AlterField(
            model_name='farmergroup',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
