# Generated by Django 4.1.5 on 2023-03-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_demofarm_contact_person_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursery',
            old_name='no_of_farmers_served',
            new_name='no_of_farmers_availaible',
        ),
    ]
