# Generated by Django 4.1.5 on 2023-03-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_rename_no_of_farmers_availaible_nursery_no_of_seedlings_availaible'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursery',
            old_name='no_of_seedlings_availaible',
            new_name='number_of_seedlings_availaible',
        ),
    ]
