# Generated by Django 4.1.5 on 2023-06-04 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_appconfig_company_approved_email_and_more'),
        ('resources', '0020_alter_farmergroup_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='county_number',
        ),
        migrations.AddField(
            model_name='event',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.county'),
        ),
    ]
